# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'numbers_round.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtMultimedia
import sys
import numbers_round
from functools import partial
from numbers_solver import getSolution



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(372, 219)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 90, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.start)
        self.target = QtWidgets.QLCDNumber(self.centralwidget)
        self.target.setGeometry(QtCore.QRect(150, 10, 71, 31))
        self.target.setDigitCount(3)
        self.target.setProperty("value", 000)
        self.target.setObjectName("target")
        self.big2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.big2.setGeometry(QtCore.QRect(110, 50, 40, 31))
        self.big2.setDigitCount(3)
        self.big2.setObjectName("big2")
        self.little1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.little1.setGeometry(QtCore.QRect(160, 50, 31, 31))
        self.little1.setDigitCount(2)
        self.little1.setObjectName("little1")
        self.little2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.little2.setGeometry(QtCore.QRect(200, 50, 31, 31))
        self.little2.setDigitCount(2)
        self.little2.setObjectName("little2")
        self.little3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.little3.setGeometry(QtCore.QRect(240, 50, 31, 31))
        self.little3.setDigitCount(2)
        self.little3.setObjectName("little3")
        self.little4 = QtWidgets.QLCDNumber(self.centralwidget)
        self.little4.setGeometry(QtCore.QRect(280, 50, 31, 31))
        self.little4.setDigitCount(2)
        self.little4.setObjectName("little4")
        self.big1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.big1.setGeometry(QtCore.QRect(60, 50, 40, 31))
        self.big1.setDigitCount(3)
        self.big1.setProperty("value", 0)
        self.big1.setObjectName("big1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 120, 300, 21))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 372, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.player = QtMultimedia.QMediaPlayer()
        url = QtCore.QUrl.fromLocalFile(QtCore.QDir.current().absoluteFilePath("sound.wav"))
        self.sound_file = QtMultimedia.QMediaContent(url)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Countdown"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", ""))

    def setDisplay(self, target, little_nums, big_nums):
        big_nums.sort()
        self.target.setProperty("value", target)
        self.big1.setProperty("value", big_nums[1])
        self.big2.setProperty("value", big_nums[0])
        self.little1.setProperty("value", little_nums[0])
        self.little2.setProperty("value", little_nums[1])
        self.little3.setProperty("value", little_nums[2])
        self.little4.setProperty("value", little_nums[3])

    def start(self):
        target = numbers_round.generate_target()
        little = numbers_round.generate_little_numbers()
        big = numbers_round.generate_big_numbers()
        self.label.setText("")
        self.setDisplay(target, little, big)
        self.pushButton.setEnabled(False)
        numbers = little + big
        self.player.setMedia(self.sound_file)
        self.player.play()
        result = getSolution(target, numbers)
        
        QtCore.QTimer.singleShot(30000, partial(self.pushButton.setEnabled, True))
        QtCore.QTimer.singleShot(30000, partial(self.label.setText, result))
        





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
